### PR TITLE
Replaced webview with Live Preview extension

### LINKED ISSUE #250: Links don't work in Preview Coverage Report
**Describe the bug**
None of the links to files work in the Preview Coverage Report

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'Preview Coverage Report' from command palette
2. Click on one of the file links
3. Nothing happens

**Expected behaviour**
As when viewing the coverage report in the browser, clicking the link should display the coverage report for that file

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macos
 - Extension Version 2.4.2
 - VSCode Version 1.41.1

### PR DESCRIPTION
**Pull request by vxdguy**
Previewing the coverage summary was lacking the CSS image files due to issues with webview security sandbox settings.  Removed all the webview code and used the Microsoft Live Preview extension to render the coverage summary file.  Code became much simpler, but introduced dependency on a 3rd party extension.

This PR should fix #250, #298, and many other closed PR's with CSS/image/javascript issues.

PR is loosely based on:

- "[How to call one extension from another](https://stackoverflow.com/a/46001467/17303633)"
- [Microsoft's Live Preview extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server), where the livePreview.start.internalPreview.atFile [command is defined](https://github.com/microsoft/vscode-livepreview/blob/3be1e2eb5c8a7b51aa4a88275ad73bb4d923432b/src/extension.ts#L169).

Apologies for not meeting all the contribution requirements.  This is my very first PR.

I've no idea how to run tests with node, nor how to use containers.  I've been learning JS/TS for about a week; it was just enough to make this work.

TODO:  package.json probably needs to be updated to show a dependency on the **[ms-vscode.live-server](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server)** extension.

Anyway, the attached animated shows me press ctrl-shift-7 to enable gutter colorization, followed by ctrl-shift-6 to preview the coverage summary in a Live Preview window.

View with Live Preview

### CODE REVIEW

**Comment by vxdguy** [comment]
@ryanluker, the PR doesn't pass the builds.  The MacOS and Windows builds looks like they were cancelled.  The Ubuntu build is failing tests; I'm not the best person to write javascript test due to zero experience with javascript testing and a week's worth of javascript/typescript experience.

**Comment by ryanluker** [comment]
@vxdguy I took a bit of a look last weekend but forgot to post here that I almost had something working for the tests. I will tinker a bit more today and see where I get to around getting those cleaned up.

**Comment by ryanluker** [comment]
@vxdguy Should be all fixed now with these 3 commits, after you take a look I can approve, and we will get this merged in!
https://github.com/ryanluker/vscode-coverage-gutters/pull/363/commits/a4736fae52b893e13e06c6f59abb5ce15812ab36 https://github.com/ryanluker/vscode-coverage-gutters/pull/363/commits/46df75d002cb7342423ec3fd5ce545db36ccf39c https://github.com/ryanluker/vscode-coverage-gutters/pull/363/commits/51fa3e8c46b9a7c89929b1e193e6eb69c7fdebe0

One question around the live preview, I tried it out locally, and I assume this what the in IDE browser should look like?
Screenshot from 2022-04-24 10-26-00

**Comment by ryanluker** [comment]
@mattseddon Do you by chance know how to programmatically interact with the live preview editor, https://github.com/microsoft/vscode-livepreview?
I wasn't able to see it listed anywhere when I debugged locally (usually when you access the `vscode.window` you can see the text documents and make assertions. I was looking to add better assertions than just checking if the extension is active or not 🤔.
https://github.com/ryanluker/vscode-coverage-gutters/pull/363/files#diff-e11f5552a6417cfc03e85116d67d338dd473153531dcd834d80fa2a0a19bd72bL22-L24

**Comment by mattseddon** [comment]
> https://github.com/microsoft/vscode-livepreview

👋🏻 . Webviews are a PITA to test and that's if you have access to the `WebviewPanel` that they are created inside. At least then you can easily test "Whether the panel is visible." and "Whether the panel is active (focused by the user).". It seems like there is no API exposed by `ms-vscode.live-server` so IMO you have two options for this assertion: `// Look to see if the webview is open and showing preview coverage` 

1. Head down this rabbit hole: https://github.com/webdriverio-community/wdio-vscode-service
2. Close all of the editors at the start of the test with `await commands.executeCommand('workbench.action.closeAllEditors')` and then check `window.visibleTextEditors` and `window.activeTextEditor` after you've opened the preview. The inside of the webview will still be a black box though.

Hope this helps. LMK if you need any clarification or further details.

👍🏻

**Comment by ryanluker** [comment]
> > https://github.com/microsoft/vscode-livepreview
> 
> 👋🏻 . Webviews are a PITA to test and that's if you have access to the `WebviewPanel` that they are created inside. At least then you can easily test "Whether the panel is visible." and "Whether the panel is active (focused by the user).". It seems like there is no API exposed by `ms-vscode.live-server` so IMO you have two options for this assertion: `// Look to see if the webview is open and showing preview coverage`
> 
> 1. Head down this rabbit hole: https://github.com/webdriverio-community/wdio-vscode-service
> 2. Close all of the editors at the start of the test with `await commands.executeCommand('workbench.action.closeAllEditors')` and then check `window.visibleTextEditors` and `window.activeTextEditor` after you've opened the preview. The inside of the webview will still be a black box though.
> 
> Hope this helps. LMK if you need any clarification or further details.
> 
> 👍🏻

Yeah I assumed it was PITA when I could find no way to interact with it programmically via the vscode.window or the getExtension helper 😢. Thanks as always @mattseddon 👋🏻!

**Review by ryanluker — APPROVED** [review]
Thanks again for the contribution @vxdguy!

**Pull request merged**
