### PR TITLE
Add maintainer websites for +5 commits

### PR DESCRIPTION
**Pull request by ryanluker**
### Description
Sharing a bit of the visibility around who helps maintain this extension (not fair for just me to be present!)
Not everyone had a website to promote though, so please ping here with the preferred link (github, twitter, mastadon, etc).
https://github.com/ryanluker/vscode-coverage-gutters/graphs/contributors

Specifically looking for info from:
@mattseddon 
@timagixe 
@pdfowler 
@amatosov-rbx 

I will leave the PR open until the next release to give people time to get back to me 😁.

### CODE REVIEW

**Comment by mattseddon** [comment]
Hi, @ryanluker. I don't have a personal website and with a busy job and two young sons I don't have time to make one 😅.  No worries on leaving me off the list or you can add my GH profile. Up to you 👍🏻.

**Comment by timagixe** [comment]
Hi @ryanluker, thank you for sharing the visibility around the contributors of the extension. As I don't have a personal website or blog, I would be thankful for sharing my GH profile.

**Comment by ryanluker** [comment]
> Hi, @ryanluker. I don't have a personal website and with a busy job and two young sons I don't have time to make one sweat_smile. No worries on leaving me off the list or you can add my GH profile. Up to you 👍🏻.

No worries @mattseddon kids are rewarding enough (and a hand full... 😅).
I appreciate the times you are able to answer my random vscode extension developer questions, hah... I will definitely add your GH handle 👍🏻 .

**Comment by ryanluker** [comment]
> Hi @ryanluker, thank you for sharing the visibility around the contributors of the extension. As I don't have a personal website or blog, I would be thankful for sharing my GH profile.

Sounds good @timagixe , adding your github profile.

**Pull request merged**
