### PR TITLE
Bugfix: Normalize workspaceFolder name

### PR DESCRIPTION
**Pull request by kh2se2013**
workspaceFolder name with case-sensitive cause match failed

### CODE REVIEW

**Comment by ryanluker** [comment]
@kh2se2013 Thanks for the pull request! Is this similar the issue brought up here?
@Peppie23 https://github.com/ryanluker/vscode-coverage-gutters/issues/188#issuecomment-544208927

Side note: there is an issue with github actions running builds on forked repositories that I will have to look into...

**Comment by ryanluker** [comment]
@kh2se2013 Github actions for forked repositories is fixed https://github.com/ryanluker/vscode-coverage-gutters/pull/242 once you get back to me with an answer for https://github.com/ryanluker/vscode-coverage-gutters/pull/241#issuecomment-544293183 we can adjust or merge this into master and I will make a quick release for `2.4.2`.

**Comment by kh2se2013** [comment]
Very nice vscode extension

**Comment by kh2se2013** [comment]
> @kh2se2013 Thanks for the pull request! Is this similar the issue brought up here?
> @Peppie23 [#188 (comment)](https://github.com/ryanluker/vscode-coverage-gutters/issues/188#issuecomment-544208927)
> 
> Side note: there is an issue with github actions running builds on forked repositories that I will have to look into...

LGTM

Very nice vscode extension

**Comment by ryanluker** [comment]
@kh2se2013 excellent, thanks again for the fix!
`2.4.2` should go out soon once I get around to finalising the testing.

**Pull request merged**
