### PR TITLE
Fails to find lcov.info file in path with directories starting with dot

### PR DESCRIPTION
**Pull request by Chcap**
## Issues:
#92 

## Info:
Hello, I simply added the `dot` option and check it in a test :)

### CODE REVIEW

**Comment by ryanluker** [comment]
@Chcap Thanks alot for putting this up 😄. I will check this out locally and test on windows 10 and ubuntu. Travis-CI builds seem to be failing though, I will take a peak at that as well.

**Comment by ryanluker** [comment]
@Chcap ahh microsoft broke the build https://github.com/Microsoft/vscode/issues/33998 I will add 
 the package they mentioned to this PR to fix it.

**Comment by ryanluker** [comment]
@Chcap Looks good to me after testing it a bit... Once the CI checks pass I will merge and create a release, thanks again for taking the time to fix this 😄 !

**Comment by Chcap** [comment]
Thanks for the quick release ! :)

**Pull request merged**
