### PR TITLE
Allow multiple sections per file path

### PR DESCRIPTION
**Pull request by ryanluker**
@justarandomgeek FYI
Related Issue: #245 
Related PR: #246 

## Work
- [x] Adjust section finding and rendering to operate on multiple sections
- [x] Deduplicate the coverage before creating editor decorations
- [x] Add test coverage for the scenario and or adjust the current nodejs one

### CODE REVIEW

**Comment by justarandomgeek** [comment]
I've discovered another minor issue related to this: when some tests include a DA line with 0 hits it still gets a red highlight even if another test does hit that line. In fact, it seems in general it's just stacking the highlights of all the tests currently, so i've turned the opacity down and it nicely hightlights how many tests hit a given line, but the reds ruin the effect a bit! I guess it needs to properly total up the hitcounts per line from each test instead of just stacking all of them for this to work.

**Comment by ryanluker** [comment]
@justarandomgeek Ahhh interesting, with the new many sections style it must be duplicating the decorations on top of each other... Definitely a bug and I believe the logic should simply take the most "positive" result as what is showed in the editor (EG: If you have 5 coverages for a single line, 4 no coverage and 1 full coverage then the 1 full coverage should be the only one displayed).

Thoughts on this?

**Comment by justarandomgeek** [comment]
Yeah, for line coverage any test hitting it should be enough to count as "full". If/when you eventually display the actual hit counts, it should be the total of all the tests that hit that line. I'm not currently generating branch coverage records (it's impractical in Lua within the restrictions of Factorio's environment), but I would think for branches you'd collect up all the branch records for a given line and combine them by the branch numbers to eventually decide on full/partial/no coverage. (I'm also generating function hit counts now, but so far only for functions that get called, and those don't seem to display anyway, which probably belongs in its own issue, if you don't already have one for that!)

**Comment by ryanluker** [comment]
@justarandomgeek thanks for the extra info! All good points you made there, on the hit count not being shown... that is known future enhancement and logged here :grin: https://github.com/ryanluker/vscode-coverage-gutters/issues/194

**Comment by ryanluker** [comment]
@justarandomgeek the duplicate removing can be found here https://github.com/ryanluker/vscode-coverage-gutters/pull/247/commits/d2e86a3077e96b562ab72ce859822d0daf7f9563

Thanks again for submitting the issue! I will do a release sometime within a week that will include these changes :grin: .

**Pull request merged**
